name: automodeler
dependencies:
- appnope=0.1.0=py34_0
- boto=2.39.0=py34_0
- cloog=0.18.0=0
- cython=0.21.1=py34_0
- dateutil=2.4.1=py34_0
- decorator=4.0.6=py34_0
- freetype=2.5.5=0
- gcc=4.8.5=3
- gmp=5.1.2=6
- ipython=4.1.1=py34_0
- ipython_genutils=0.1.0=py34_0
- isl=0.12.2=1
- libpng=1.6.17=0
- matplotlib=1.4.3=np19py34_3
- mkl=11.3.1=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- nose=1.3.7=py34_0
- numexpr=2.4.4=np19py34_0
- numpy=1.9.3=py34_1
- openssl=1.0.2f=0
- pandas=0.16.2=np19py34_0
- path.py=8.1.2=py34_1
- pexpect=3.3=py34_0
- pickleshare=0.5=py34_0
- pip=8.0.2=py34_0
- pyparsing=2.0.3=py34_0
- pyqt=4.11.4=py34_1
- python=3.4.4=0
- python-dateutil=2.4.2=py34_0
- python.app=1.2=py34_4
- pytz=2015.7=py34_0
- qt=4.8.7=1
- readline=6.2=2
- scikit-learn=0.16.1=np19py34_0
- scipy=0.16.0=np19py34_1
- seaborn=0.5.1=np19py34_0
- setuptools=19.6.2=py34_0
- simplegeneric=0.8.1=py34_0
- sip=4.16.9=py34_0
- six=1.10.0=py34_0
- sqlalchemy=1.0.12=py34_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- traitlets=4.1.0=py34_0
- wheel=0.29.0=py34_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - automodeler (/Users/kcrum/src/automodeler)==3.1+3.g8853f31.dirty
  - boto3==1.2.3
  - botocore==1.3.27
  - civis (/Users/kcrum/src/civis-client)==2.0.0
  - civis-io (/Users/kcrum/src/civis-io)==0.1
  - docutils==0.12
  - glmnet (/Users/kcrum/src/python-glmnet)==0.0.1
  - hipchat==0.0.1
  - ipdb==0.8.3
  - ipython-genutils==0.1.0
  - jmespath==0.9.0
  - patsy==0.4.1
  - psycopg2==2.6.1
  - pybayestree==1.0
  - pyds (/Users/kcrum/src/pyds)==2.0
  - requests==2.7.0
  - retrying==1.3.3
  - rpy2==2.7.8
  - statsmodels==0.7.0

